config/routes.rb
Rails.application.routes.draw do
  scope module: 'session' do
    get 'login', action: 'new'
    post 'login', action: 'create'
    get 'logout', action: 'destroy'
  end

  resources :launchpad, only: [:index]

  resources :teams, only: [:create], param: :uid do
    resources :events, only: [:index]
    resources :projects, only: [:index, :show], param: :uid
    resources :users, only: [:index], param: :uid
  end

  resources :projects, only: [], param: :uid do
    resources :todos, only: [:show], param: :uid
    resources :todolist, only: [:show], param: :uid
  end

  root 'events#index'
end

app/models/project.rb
class Project < ApplicationUidRecord
  acts_as_paranoid without_default_scope: true

  belongs_to :team
  has_many :todolists
  has_many :todos

  validates_presence_of :name

  has_many :events, as: :resource
  attr_accessor :operator
  after_create lambda { |obj|
    generate_default_todolist!
    trigger_add_event user_id: obj.operator.try(:id).to_i, project_id: obj.id
  }
  after_destroy lambda { |obj|
    trigger_remove_event user_id: obj.operator.try(:id).to_i, project_id: obj.id
  }

  def generate_todolist!(name)
    todolists.create! name: name, user_id: operator.id, operator: operator, project_uid: uid
  end

  private

  def generate_default_todolist!
    generate_todolist! I18n.t(:default_todolist)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :require_team
  before_action :set_current_team, only: [:index]

  def index
    @projects = Project.where(params.permit(:team_uid))
  end

  def show
    @project = Project.find_by(params.permit(:team_uid, :uid))
  end

  private

  def set_current_team
    session[:team_id] = Team.find_by(uid: params[:team_uid]).id
  end
end

app/views/projects/index.html.erb
<div class="container pt100">
  <div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">
      <div class="row">
        <% @projects && @projects.each do |project| %>
          <div class="col-xs-6 col-lg-4">
            <h2><%= project.name %></h2>
            <p><%= project.description %></p>
            <p><%= link_to '查看', team_project_path(current_team, project) %></p>
          </div><!--/.col-xs-6.col-lg-4-->
        <% end %>
      </div><!--/row-->
    </div><!--/.col-xs-12.col-sm-9-->
  </div><!--/row-->
</div>

app/views/projects/show.html.erb
<div class="container pt100">
  <div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">
      <div class="row">
        <div class="col-xs-6 col-lg-4">
          <h2><%= @project.name %></h2>
          <p><%= @project.description %></p>
        </div><!--/.col-xs-6.col-lg-4-->
      </div><!--/row-->
    </div><!--/.col-xs-12.col-sm-9-->
  </div><!--/row-->
</div>


<div class="container todolist">
  <div class="table-responsive">
    <table class="table table-striped">
      <tr>
        <th>任务创建者</th>
        <th>标题</th>
        <th>描述</th>
        <th>查看</th>
      </tr>
      <% @project.todolists.present? && @project.todolists.first.todos.each do |todo| %>
        <tr>
          <th><%= todo.user.name %></th>
          <th><%= todo.name %></th>
          <th><%= todo.description %></th>
          <th><%= link_to '查看', project_todo_path(@project, todo) %></th>
        </tr>
      <% end %>
    </table>
  </div>
</div>