config/routes.rb
Rails.application.routes.draw do
  scope module: 'session' do
    get 'login', action: 'new'
    post 'login', action: 'create'
    get 'logout', action: 'destroy'
  end

  resources :launchpad, only: [:index]

  resources :teams, only: [:create], param: :uid do
    resources :events, only: [:index]
    resources :projects, only: [:index, :show], param: :uid
    resources :users, only: [:index], param: :uid
  end

  resources :projects, only: [], param: :uid do
    resources :todos, only: [:show], param: :uid
    resources :todolist, only: [:show], param: :uid
  end

  root 'events#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventsDemo</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Project name</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= menu?('projects') ? 'active' : '' %>">
          <%= link_to '项目', team_projects_path(current_team) %>
        </li>
        <li class="<%= menu?('events') ? 'active' : '' %>">
          <%= link_to '动态', team_events_path(current_team) %>
        </li>
        <li class="<%= menu?('users') ? 'active' : '' %>">
          <%= link_to '团队', team_users_path(current_team) %>
        </li>
      </ul>
    </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</nav><!-- /.navbar -->

<%= yield %>
</body>
</html>